import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";
import { Montserrat } from "next/font/google";

const montserrat = Montserrat({
  weight: ["100", "300", "500", "700"],
  subsets: ["latin"]
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={montserrat.className} suppressHydrationWarning={true}>
          <div className="container m-auto">{children}</div>
        </body>
      </html>
    </ClerkProvider>
  );
}
